version: '3'

services:
   db:
     image: mariadb
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     environment:
       MARIADB_ROOT_PASSWORD: wordpress
       MARIADB_DATABASE: wordpress
       MARIADB_USER: wordpress
       MARIADB_PASSWORD: wordpress

   # login - server: '' | username: root | password: 'wordpress'
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     links:
       - db
     environment:
       - PMA_ARBITRARY=1
     restart: always
     ports:
       - 8080:80
     volumes:
       - /sessions

   wordpress:
     depends_on:
       - db
     image: wordpress:php8.1
     volumes:
       - "./:/var/www/html/"
     links:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

# REF: docker-compose up
# Set wp-config-local with the above settings
